### PR TITLE
add Free Software Foundation

### PR DESCRIPTION
**Pull request by vyp**
What about the Free Software Foundation?

---

Also, this is off topic (because I feel it doesn't warrant creating another issue just to ask), but are things like [Project Meshnet](https://projectmeshnet.org/) also suitable here?

### CODE REVIEW

**Comment by vyp** [comment]
Also added the [Software Freedom Law Center](https://www.softwarefreedom.org/), and [Software Freedom Conservancy](https://sfconservancy.org/) too.

**Comment by vyp** [comment]
Oh and I just saw the sorted A-Z note. Didn't realise that because OSI came after SPI, so I just added to the bottom. Should I sort, or I think it might be easier if I let you sort it (assuming you accept this PR)?

**Comment by n1trux** [comment]
thank you a lot for your contribution(s)! I merged the pull request and sorted it a little.

**Comment by vyp** [comment]
Sweet, no worries.

Again, off-topic, but this might help about pidgin: https://developer.pidgin.im/ticket/3066#comment:17

**Pull request merged**
