### PR TITLE
added looooots of entries

### PR DESCRIPTION
**Pull request by boredsquirrel**

### CODE REVIEW

**Comment by boredsquirrel** [comment]
maybe linux foundation EU is missing

https://linuxfoundation.eu

**Comment by boredsquirrel** [comment]
budgie:

https://opencollective.com/buddies-of-budgie

**Comment by trytomakeyouprivate** [comment]
mobilsicher already added? dont know

https://mobilsicher.de/spenden

**Comment by boredsquirrel** [comment]
hey are you active?

**Comment by n1trux** [comment]
Thank you a lot!

**Comment by boredsquirrel** [comment]
you are welcome

**Pull request merged**
